services:
  - type: web
    name: rootshop
    env: node
    dockerfilePath: Dockerfile.render
    plan: free
    numInstances: 1
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://kylewb94:KdBm9416@mernproject.3e8aj.mongodb.net/roots?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: PAYPAL_CLIENT_ID
        value: ARWdGWvmJ7RWN33LU4Fkw8eMXJa_-kHiQXtexUFFMstQUYQC5YX3tn-GlcU6FuTmTFgDt4Aajbfgvm9N
      - key: PORT
        value: 5000

